# Generated by Django 5.1.6 on 2025-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_company_information_expence_category_income_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='price_per_hour',
            field=models.IntegerField(null=True),
        ),
    ]
