# Generated by Django 5.1.6 on 2025-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_booking_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('fees_paid', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
