# Generated by Django 5.1.6 on 2025-02-11 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_alter_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_amount', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('expence_category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.expence_category')),
            ],
        ),
    ]
