# Generated by Django 5.1.6 on 2025-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expence_category',
            name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
