# Generated by Django 5.1.6 on 2025-02-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_alter_expense_ex_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ex_amount',
            field=models.IntegerField(),
        ),
    ]
