# Generated by Django 5.1.6 on 2025-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_alter_expense_ex_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.IntegerField()),
            ],
        ),
    ]
