# Generated by Django 5.1.6 on 2025-02-21 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0014_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('7 - 9 AM', '7 - 9 AM'), ('9 - 11 AM', '9 - 11 AM'), ('11 - 2:30 PM', '11 - 2:30 PM'), ('2:30 - 6 PM', '2:30 - 6 PM')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.ground')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.timeslot')),
            ],
            options={
                'unique_together': {('ground', 'date', 'time_slot')},
            },
        ),
    ]
