# Generated by Django 5.1.6 on 2025-02-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0015_timeslot_superbooking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='superbooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='superbooking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='superbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='superbooking',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='superbooking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
