# Generated by Django 5.1.6 on 2025-02-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0016_alter_superbooking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superbooking',
            name='temp_lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
